import type { Metadata } from "next";
import { Inter, Anuphan } from "next/font/google";
import "./globals.css";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
})

const anuphan = Anuphan({
    variable: "--font-anuphan",
    subsets: ["thai", "latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="th" suppressHydrationWarning>
            <body className={`${inter.variable} ${anuphan.variable} font-sans antialiased`}>
                {children}
            </body>
        </html>
    )
}
